# Airflow home directory
# Used for mount paths
airflowHome: /opt/airflow

# Default airflow repository -- overridden by all the specific images below
defaultAirflowRepository: apache/airflow

# Default airflow tag to deploy
defaultAirflowTag: "2.7.1"

# Airflow version (Used to make some decisions based on Airflow Version being deployed)
airflowVersion: "2.7.1"

# Images
images:
  airflow:
    repository: ~
    tag: ~
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

executor: KubernetesExecutor

data:
  metadataConnection:
    user: postgres0
    pass: REPLACE_WITH_DB_PASSWORD
    protocol: postgresql
    host: REPLACE_WITH_DB_HOST
    port: 5432
    db: deb-airflow-db
    sslmode: disable

# Git sync
dags:
  gitSync:
    enabled: true
    repo: git@github.com:uche-madu/wizeline-data-engineering-bootcamp.git
    branch: main
    subPath: "capstone_project/dags"
    sshKeySecret: airflow-ssh-secret

    # Get info about known_hosts from here: https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#knownhosts
    knownHosts: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
  
# extraSecrets:
#   airflow-ssh-secret:
#     data:
#       gitSshKey: ~


# Flask secret key for Airflow Webserver: `[webserver] secret_key` in airflow.cfg
# webserverSecretKey: ~
webserverSecretKeySecretName: "airflow-webserver-secret"


# Airflow webserver settings
webserver:
  service:
    type: LoadBalancer
  
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin

postgresql:
  enabled: false

workers:
  persistence:
    size: 10Gi
    
# Airflow Triggerer Config
triggerer:
  persistence:
    # Volume size for triggerer StatefulSet
    size: 5Gi